# these are test requests for /api/account

@base_url = http://localhost:8000/api/account

@username = test acc
@password = password123
@new_password = securepassword!@#

@account_type = Student
@new_account_type = Parent

# fill in after first post
@uuid = e7bd2f1d-7cc0-4d6c-be41-04703a49f886



### create
POST {{base_url}}
Content-Type: application/json

{
	"username": "{{username}}",
	"password": "{{password}}",
	"account_type": "{{account_type}}"
}



### get by id
GET {{base_url}}/{{uuid}}

### get by username
GET {{base_url}}/{{username}}



### invalid patch - id
PATCH {{base_url}}/00000000-0000-0000-0000-000000000000
Content-Type: application/json

{
	"password": "1",
	"new_password": "2"
}

### invalid patch - password
PATCH {{base_url}}/{{uuid}}
Content-Type: application/json

{
	"password": "1",
	"new_password": "2"
}

### invalid account type patch
PATCH {{base_url}}/{{uuid}}
Content-Type: application/json

{
	"password": "{{password}}",
	"new_account_type": "lol"
}

### valid account type patch
PATCH {{base_url}}/{{uuid}}
Content-Type: application/json

{
	"password": "{{password}}",
	"new_account_type": "{{new_account_type}}"
}

### valid profile picture url patch
PATCH {{base_url}}/{{uuid}}
Content-Type: application/json

{
	"password": "{{password}}",
	"new_profile_picture_url": "https://styles.redditmedia.com/t5_2v5h6u/styles/profileIcon_vmfbuhrygxbb1.jpg?width=256&height=256&crop=256:256,smart&s=04fc700caaf056234a0eecfdcc8e53d246f9c7da"
}

### valid password patch
PATCH {{base_url}}/{{uuid}}
Content-Type: application/json

{
	"password": "{{password}}",
	"new_password": "{{new_password}}"
}



### invalid delete - id
DELETE {{base_url}}/00000000-0000-0000-0000-000000000000
Content-Type: application/json

{
	"password": "1"
}

### invalid delete - password
DELETE {{base_url}}/{{uuid}}
Content-Type: application/json

{
	"password": "1"
}

### valid delete
DELETE {{base_url}}/{{uuid}}
Content-Type: application/json

{
	"password": "{{new_password}}"
}
