# these are test requests for /api/live

@base_url = http://localhost:8000/api/live

@username = test_acc
@password = Password123!

@qwiz_id = 1

@live_qwiz_id = 58475



### info
GET {{base_url}}



### create a live qwiz
POST {{base_url}}

{
	"username": "{{username}}",
	"password": "{{password}}",
	"qwiz_id": {{qwiz_id}},
	"options": {
		"shuffle_questions": true,
		"shuffle_answers": true
	}
}



### get created live qwiz
GET {{base_url}}/{{live_qwiz_id}}



### Start live qwiz
POST {{base_url}}/{{live_qwiz_id}}/start

{
	"username": "{{username}}",
	"password": "{{password}}"
}
